added intermediate variables for plotly figures
ministryofjustice/operations-engineering-kpi-dashboard pull request #19
Opened 2024-08-14 15:22 UTC by abachleda-baca

This PR refactors the existing function, which previously returned a Plotly figure directly, by first assigning the figure to an intermediate variable, fig, before returning it.

Using an intermediate variable makes the code easier to read and understand, and it also aligns with the general practice of keeping return statements simple.

2024-08-14 16:02 UTC, tamsinforbes requested changes
Some request for consistency please - otherwise great spot

2024-08-14 16:02 UTC, tamsinforbes commented on app/services/figure_service.py
> +        return fig_stubbed_no_of_repos_with_standard_label
```suggestion
        return fig_stubbed_number_of_repositories_with_standards_label
```

2024-08-14 16:02 UTC, tamsinforbes commented on app/services/figure_service.py
> +        fig_stubbed_no_of_repos_with_standard_label.add_hline(y=0)
```suggestion
        fig_stubbed_number_of_repositories_with_standards_label.add_hline(y=0)
```

2024-08-14 16:02 UTC, tamsinforbes commented on app/services/figure_service.py
> +        fig_no_of_repos_with_standard_label.add_hline(y=0)
```suggestion
        fig_number_of_repositories_with_standards_label.add_hline(y=0)
```

2024-08-14 16:02 UTC, tamsinforbes commented on app/services/figure_service.py
> +        return fig_no_of_repos_with_standard_label
```suggestion
        return fig_number_of_repositories_with_standards_label
```

2024-08-15 08:38 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_no_of_repos_with_standard_label = px.line(
Updated

2024-08-15 08:38 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_stubbed_no_of_repos_with_standard_label = px.line(
Updated

2024-08-15 08:38 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_get_stubbed_no_of_repos_archived_by_automation = px.line(
Updated

2024-08-15 08:38 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_get_stubbed_no_of_repos_archived_by_automation.add_hline(y=0)
Updated

2024-08-15 08:38 UTC, abachleda-baca commented on app/services/figure_service.py
> +        return fig_get_stubbed_no_of_repos_archived_by_automation
Updated

2024-08-15 08:39 UTC, abachleda-baca commented on app/services/figure_service.py
> +        return fig_stubbed_sentry_trans_used
Updated

2024-08-15 08:39 UTC, abachleda-baca commented on app/services/figure_service.py
> +        return fig_stubbed_no_of_repos_with_standard_label
Updated

2024-08-15 08:39 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_stubbed_no_of_repos_with_standard_label.add_hline(y=0)
Updated

2024-08-15 08:39 UTC, abachleda-baca commented on app/services/figure_service.py
> +        fig_no_of_repos_with_standard_label.add_hline(y=0)
Updated

2024-08-15 08:39 UTC, abachleda-baca commented on app/services/figure_service.py
> +        return fig_no_of_repos_with_standard_label
Updated

2024-08-15 09:48 UTC, merged